sut:
  build: tests/.
  dockerfile: Dockerfile.test
  links:
    - web1804-php7
    - web1604-php7

web1804-php7:
  build: .
  dockerfile: ./1804/Dockerfile
  environment:
    - MYSQL_ADMIN_PASS=password
  ports:
    - "3000:80"
    - "3001:3306"

web1604-php7:
  build: .
  dockerfile: ./1604/Dockerfile
  environment:
    - MYSQL_ADMIN_PASS=password
  ports:
    - "3002:80"
    - "3004:3306"
